package com.dbi.backend.entity;

public enum UserRole {
    BENEFICIARY,
    FIELD_VERIFICATION_OFFICER,
    DEPT_ADMIN,
    SYSTEM_ADMIN,
    MONITORING_AUDIT_OFFICER,
    SCHEME_SANCTIONING_AUTHORITY
}
